manager:
  mode: 1 # 0 - training, 1 - evaluation, 2 - training and evaluation
  selected_model: "yolo"
  selected_dataset_train: "coco" # Dataset to train or transfer learning on
  selected_dataset_eval: "coco"
  models:
    yolo:
      name: "yolo"
      datasets_train: ["coco", "bdd100k"]
      datasets_eval: ["coco", "bdd100k"]
    faster-rcnn:
      name: "faster-rcnn"
      datasets_train: ["coco", "bdd100k"]
      datasets_eval: ["coco", "bdd100k"]